conformal/spectrwm

- linux/Makefile
A bunch of improvements to how linking is handled on Linux:
* reduce the number of libraries that libswmhack is linked against
* link libswmhack against libdl (needed because of `dlopen()` and friends)
* use `pkg-config` instead of hardcoding information in the `Makefile`
* use `--as-needed` to avoid unnecessary linking
Tested on Debian, Fedora and Arch.
> linux: improve linking

- linux/Makefile
Enable PIE (position-independent executables) on Linux.
This should be merged on top of https://github.com/conformal/spectrwm/pull/140, as it builds on it.
Build-tested on Debian, Fedora and Arch. Run-tested on Debian and Fedora.
> linux: Enable PIE

- spectrwm.c
Match the type of the array to the `format` argument (32).
Could change the format to 16, but the value is documented to be a `CARD32`, so may as well use 32 bit input.
> Correct size for WM_STATE

- spectrwm.c
Otherwise child processes inherit SIG_IGN for SIGPIPE, which can have
unexpected consequences. e.g. when performing pkg_add -ui in an xterm
spawned by spectrwm some spurious EPIPE errors find their way to the
output due to pkg_add expecting a sane default signal environment.
<pre>
$ pkg_add -nuix vim
quirks-2.261 signed on 2016-10-11T14:06:48Z
Error from http://ftp.fr.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/vim-8.0.0004-gtk2-perl-python3-ruby.tgz
signify: write to stdout: Broken pipe
Error from http://ftp.fr.openbsd.org/pub/OpenBSD/snapshots/packages/amd64/vim-8.0.0004-gtk2-lua.tgz
signify: write to stdout: Broken pipe
[...]
</pre>
> Reset SIGPIPE before execvp().

- README.md
Screenshot links are broken. Removing the line breaks fixes it.
> remove linebreaks to fix image links

- README.md
Hi,
The name of the program xmonad was also provided where the link was meant to (according to Markdown syntax) be provided. The result was that this is what people see when reading the README:
> [xmonad](http://xmonad.org xmonad)
This commit merely fixes this issue. 
Thanks for your time,
Brenton
> Fixing link for xmonad in README

- spectrwm.c
Silences the following warning with `GCC7` and `-O2`.
```
cc -Wl,--as-needed -fPIC -shared  -Wl,-soname,libswmhack.so.0.0 -o libswmhack.so.0.0 swm_hack.so -lX11  -ldl 
../spectrwm.c: In function ‘search_win’:
../spectrwm.c:6058:26: warning: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 8 [-Wformat-truncation=]
snprintf(s, sizeof s, "%d", i);
^~
../spectrwm.c:6058:25: note: directive argument in the range [1, 2147483647]
snprintf(s, sizeof s, "%d", i);
^~~~
../spectrwm.c:6058:3: note: ‘snprintf’ output between 2 and 11 bytes into a destination of size 8
snprintf(s, sizeof s, "%d", i);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Please review.
> Silence -Wformat-truncation= warning with gcc7

- spectrwm.conf
Update example configuration file with new options bar_color_selected
and bar_font_color_selected.
Also update the example with dmenu to use the new colors.
Add two other dmenu examples, search and name_workspace, that was added
to the manual with the same commit as the new color options.
This was not done as part of the 22167bcf2fd2cbb22ffe89817f9c279804c8e0af  commit.
> Update config with new color options

- spectrwm.c
If the status bar script returns NUL as the first character through
stdin, spectrwm is prone to an out of boundary access. Depending on
the memory layout of the machine, it could turn into an OOB write.
The fix is simple: If the string is empty, do not further check for
newline character.
Signed-off-by: Tobias Stoeckmann <tobias@stoeckmann.org>
> Fix OOB while reading bar input.

- spectrwm.c
For some reason that I still need to figure out, on one of my boxes the X font creation does not work.
However, something happens that I think according to ftp://www.x.org/pub/current/doc/man/man3/XCreateFontSet.3.xhtml shouldn't be possible:
* `XCreateFontSet` returns `NULL`, so `bar_fs` is `NULL`
* `num_missing_charsets` is set to `1`
* `default_string` is set to `NULL`
This leads to a segmentation fault when `strcmp(default_string, "")` is called.
By checking whether `bar_fs` is `NULL` prior to accessing `default_string`, this is circumvented.
> fix segmentation fault in font creation

- spectrwm.1
This silences the following warnings reported by mandoc.
```
man: /usr/man/man1/spectrwm.1.gz:653:10: STYLE: no blank before trailing delimiter: Cm M-,
man: /usr/man/man1/spectrwm.1.gz:655:10: STYLE: no blank before trailing delimiter: Cm M-.
man: /usr/man/man1/spectrwm.1.gz:657:12: STYLE: no blank before trailing delimiter: Cm M-S-,
man: /usr/man/man1/spectrwm.1.gz:659:12: STYLE: no blank before trailing delimiter: Cm M-S-.
man: /usr/man/man1/spectrwm.1.gz:761:10: STYLE: no blank before trailing delimiter: Cm M-]
man: /usr/man/man1/spectrwm.1.gz:765:12: STYLE: no blank before trailing delimiter: Cm M-S-]
```
I did test this on my system, but please review to make sure its correct, thanks!
> spectrwm.1: Silence mandoc style warnings.

- spectrwm.1
Silences two more mandoc lint warnings.
```
man: /usr/man/man1/spectrwm.1.gz:231:18: WARNING: new sentence, new line
man: /usr/man/man1/spectrwm.1.gz:986:71: WARNING: new sentence, new line
```
```
new sentence, new line
(mdoc) A new sentence starts in the middle of a text line. Start it on a
new input line to help formatters produce correct spacing
```
https://man.openbsd.org/mandoc.1
> spectrwm.1: Silence mandoc warnings

- baraction.sh
- linux/tree.h
Trivial, just removes some trailing whitespace.
> Whitespace

- NEWS.md
Since 3.0.0, release notes for spectrwm are already being
compiled and ultimately published at
https://github.com/conformal/spectrwm/releases
but it would be useful if they were included in the release
tarball themselves as well.
The contents of the NEWS.md file are taken straight from the
page mentioned above, with only very minor editing.
> NEWS: Add release notes

- spectrwm.c
find_frame_window() has been introduced as part of commit da92f07e, and
has never been used.
> Remove unused function.

- spectrwm.c
Silence the warning below, although it is highly unlikely that one encounters an issue related to it.
```
spectrwm.c:6300:51: warning: The right operand of '-' is a garbage value
(bar_fs_extents->max_logical_extent.height -
^
```
> Silence warning reported by the clang static analyzer.

- spectrwm.c
In get_binding_keycode() a uint8_t loop variable was incremented in a
for loop.  The variable would overflow right before the loop's
condition was met.  Therefore the loop would never terminate.
To avoid the infinite loop the condition has to be checked before the
increment operation and not afterwards.
> Fix infinite loop due to unsigned integer overflow.

- spectrwm.c
On OpenBSD, restrict system operations as soon as possible using `pledge(2)`. Drop some 'promises'  even earlier.
I've been running with this on OpenBSD current for some time without noticing any regression.
> pledge() earlier

- spectrwm.1
- spectrwm.c
This is a proposed enhancement for the status bar. It is enabled with bar_split = 1
This will split the bar text into 3 parts:
- The left part which is left justified.
- The right part which is right justified.
- The middle part which occupies the free space between the two and is centered within that space.
The split is done with the key sequences +\ and +/ within the bar_format.
+\  marks the start of the middle text
+/ marks the start of the right text 
Example of a split bar format:
bar_format = +L +\ +W +/ +A
In addition, 4 color resources are defined  to control the background and foreground color of the middle add right part:
- bar_color_middle
- bar_color_right
- bar_font_color_middle
- bar_font_color_right
The left part use the default resources. 
Also the value of bar_justify is …
> Several Improvements to the status bar. (multi-sections, text markup, unicode icons)

- spectrwm.1
- spectrwm.c
New conf search order:
1) $XDG_CONFIG_HOME/spectrwm/spectrwm.conf
2) ~/.config/spectrwm/spectrwm.conf
(if $XDG_CONFIG_HOME is either not set or empty)
3) ~/.spectrwm.conf
4) $XDG_CONFIG_DIRS/spectrwm/spectrwm.conf
(each colon-separated directory in $XDG_CONFIG_DIRS)
5) /etc/xdg/spectrwm/spectrwm.conf
(if $XDG_CONFIG_DIRS is either not set or empty)
6) /etc/spectrwm.conf
Closes #153
> Add support for XDG Base Directory Specification.

- spectrwm.c
This patch fix a buffer overflow introduced by the multisection commit in the function bar_strlcat_esc. This function can overwrite the ending '\0' in the destination string when the source overflows the destination. This fixes the issue.
> Fix buffer overflow in bar_strlcat_esc

- spectrwm.c
line 1785 - Wrong type
line 2486 - Division by zero
line 2575 - Uninitialized argument value
line 2583 - Uninitialized argument value
line 2595 - Uninitialized argument value
line 2597 - Uninitialized argument value
line 3468 - Wrong type
line 3730 - Dereference of null pointer
line 6065 - Result of operation is garbage or undefined
line 9374 - Wrong type
line 12446 - Possible null pointer dereference
> Silence (Clang) static analyzer warnings.

- spectrwm.c
Restrict spectrwm even further following work from matthieu@ on font
caches: https://undeadly.org/cgi?action=article;sid=20180717074543
> Reduce number of pledge(2) promises (OpenBSD only)

- lib/Makefile
I'm currently running spectrwm HEAD on OpenBSD current. When starting a tool from urxvt I'm seeing the following:
```
$ ncspot
ncspot:/usr/local/lib/libswmhack.so.1.0: undefined symbol 'XKeysymToKeycode'
```
It seems that `XKeysymToKeycode` is seen as a normal symbol while actually it is a function:
```
$ objdump -T libswmhack.so.1.0.orig
libswmhack.so.1.0.orig:     file format elf64-x86-64
DYNAMIC SYMBOL TABLE:
0000000000000000  w   D  *UND*	0000000000000000 _Jv_RegisterClasses
0000000000000000  w   D  *UND*	0000000000000000 __cxa_atexit
0000000000000000  w   D  *UND*	0000000000000000 __cxa_finalize
0000000000000000  w   D  *UND*	0000000000000000 _thread_atfork
0000000000000000      D  *UND*	0000000000000000 XKeysymToKeycode
0000000000000000      D  *UND*	0000000000000000 __sF …
```
> Link libswmhack against libX11

- spectrwm.1
Sometimes an OS ignores `LD_PRELOAD`, e.g. OpenBSD does this for set-user-ID and set-group-ID executables, causing `autorun` to behave differently. Explain this - and provide a workaround - in `spectrwm.1`,
Inspired by #281.
> Add workaround to man page for OS ignoring LD_PRELOAD

- spectrwm.c
XftTextExtentsUtf8 computes the pixel extents and stores them in a XGlyphInfo data type. The true "width" of a Xft glyph is found in the xOff member of the latter structure.
This fixes the (dis)appearing space when switching workspace (#264).
> Fix width calculation of a Xft glyph

- linux/Makefile
Submitted on behalf of Helmut Grohne, who provided the patch as part of his effort to fix [Debian bug #928902](https://bugs.debian.org/928902). This patch is necessary for spectrwm to cross-build correctly.
> linux: Accept user-provided pkg-config command

- spectrwm.c
@marcopeereboom Passing this fix by you first since it involves removing your hack ;)
ICCCM permits clients to change any property on its withdrawn windows.
If a client maps a withdrawn window again, the window manager should
treat it as new.
> Withdrawn window fix

- spectrwm.c
Hello,
Spectrwm is crashing on my OpenBSD Sparc64 box.
ktrace:
```
70801 spectrwm CALL  open(0x7904d18380,0x10002<O_RDWR|O_CLOEXEC>)
70801 spectrwm NAMI  "/var/cache/fontconfig//7908e75dfa020c169504380270e5263a-be64.cache-7"
70801 spectrwm PLDG  open, "wpath", errno 1 Operation not permitted
70801 spectrwm PSIG  SIGABRT SIG_DFL
```
This pull request adds the wpath pledge. This fixed the crash.
> Add "wpath" pledge for OpenBSD on Sparc64

- baraction.sh
The first line of iostat(8) displays the stats from the time of the last reboot.  Show the current stats instead by grabbing and displaying
the second line.
From mglocker@
> openbsd: print current cpu stats

- spectrwm.1
- spectrwm.c
#379: If `disable_border=always`, remove borders from maximized windows, even if the bar is enabled.
> Disable border for max windows if disable_border=always (closes #379)

- linux/linux.c
- osx/osx.c
This include is unused and not shipped by musl.
Gentoo Bug: https://bugs.gentoo.org/712976
Reference: https://wiki.musl-libc.org/faq.html#Q:-When-compiling-something-against-musl,-I-get-error-messages-about-%3Ccode%3Esys/cdefs.h%3C/code%3E
> linux: Don't include sys/cdefs.h

- linux/Makefile
With `make(1)` variables set with `:=` are expanded when they are set and variables set with `=` are expanded when they are used.
Reference: https://www.gnu.org/software/make/manual/make.html#Flavors
> linux: Expand Makefile variables when set

- linux/linux.c
This is not supported in future clang versions.
error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype
Reference: https://archives.gentoo.org/gentoo-dev/message/dd9f2d3082b8b6f8dfbccb0639e6e240
> linux: Fix build with clang 16

- spectrwm.1
This hopefully lowers the entrance barrier to Spectrwm. Especially the distinction between (1) maximized, (2) full-screen states and (3) maximized stacking mode are quite subtle.
I could also address #454 if it would be welcome.
> Add stack modes and window states to manpage

- spectrwm.1
The correct sequence for a backslash is `'\e'`, not `'\\'`. The right thing is already done in a number of places; fix the remaining spots.
Spotted by Lintian.
> Escape backslashes correctly in manual page

- spectrwm.1
- spectrwm.c
- spectrwm.conf
I recently started using a monitor in a vertical orientation and felt we could use the xrandr rotation information to improve on the vertical/horizontal layouts.
This PR implements a new aptly-named "workspace_autorotate" configuration entry and behavior intended to improve handling of rotated displays.
When enabled, and when moving workspaces across regions, auto-rotate vertical/horizontal layouts based on rotation data from xrandr(1).
This results in the following nice properties:
- If the workspace is initialized on a vertical display, default to a horizontal split, which more equally balances the windows.
- When moving a vertical layout on a vertical display, auto-switch the layout to horizontal (and vice-versa).
This is half-intelligent too: when moving between two visible regions, …
> Implement workspace_autorotate

- linux/Makefile
Setting `-g` should be up to the user and can be set in the `CFLAGS` environment variable. Building debugging symbols is slower especially on weaker hardware and will cause an increase in disk writes. Additionally many distros will just strip the symbols away making this wasteful.
> linux: Don't force building debugging symbols

- spectrwm.c
This fixes a couple of issues when using legacy fonts.
> Legacy font fixes

- spectrwm.1
- spectrwm.c
I wanted the bar of focused screens to 'pop' a little bit more. We can set the bar border color, but that didn't give me enough visual cue unless I made it too big.
For this reason I introduced two new options to change the foreground/background colors of the bar depending on the focused region which after a few tries I came to really like. This allowed me to disable the bar border completely. See this clip to see the behavior with two screens, alternating in focus:
https://www.thregr.org/~wavexx/tmp/spectrwm-test.webp (uploaded elsewhere due to gh refusing webp)
Both default to the same focused colors (without suffix), resulting in no change in behavior without the extra new customization.
I currently based this on `release3.5` as I wanted to test the new tweaks to the region rotation …
> Add new `bar_color_unfocus` and `bar_font_color_unfocus` options.

- spectrwm.1
- spectrwm.html
Provides users with a convenient way to opt-out of `libswmhack.so` usage if they so desire.
> Improve documentation around libswmhack.so

- spectrwm.1
- spectrwm.c
- spectrwm.conf
Add the relevant config options `color_urgent*`. The default colors were picked completely arbitrarily
> Urgent windows border color

- spectrwm.c
Currently, if restarting with the `restart_of_day` function, any autoruns in the user config file are executed again. Since the general usecase for this function is to restart spectrwm while preserving layout settings (#172, #395, #445), it doesn't make sense to execute autoruns again.
> Ignore autoruns if restarting with `restart_of_day`
